/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package deposition

// Klasa zawierająca dane nadawcy przelewu krajowego używana w żądaniach PIS / Domestic PIS services Sender Data Class
type SenderPisDomestic struct {

	AccountNumber *AccountNumber `json:"accountNumber,omitempty"`

	NameAddress *NameAddress `json:"nameAddress,omitempty"`
}
