/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package deposition

import (
	"time"
)

// Klasa zawierająca zwrotne metadane / Metadata Class
type ResponseHeader struct {

	// Data odpowiedzi, format: YYYY-MM-DDThh:mm:ss[.mmm] / Send date
	SendDate time.Time `json:"sendDate,omitempty"`

	// Znacznik określający czy odpowiedz zostanie przekazana w formie wywołania zwrotnego. true - gdy odpowiedz w formie wywołania zwrotnego. Inna dopuszczalna wartość to false.
	IsCallback bool `json:"isCallback,omitempty"`

	// Identyfikator żądania otrzymanego od TPP / Identifier of request received from TPP
	RequestId string `json:"requestId,omitempty"`
}
