/*
 * PKO BP API 2.1.1
 *
 * Specyfikacja interfejsu dla usług świadczonych przez ASPSP w oparciu o dostęp do rachunków płatniczych. Opracowane przez Związek Banków Polskich i podmioty współpracujące / Interface specification for services provided by ASPSP based on access to payment accounts. Prepared by the Polish Bank Association and its affiliates
 *
 * API version: 1.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package deposition

// Klasa zlecenia przelewu krajowego / Domestic Transfer Request Class
type PaymentDomesticRequest struct {

	Sender *SenderPisDomestic `json:"sender"`

	// Droga jaką przelew ma być rozliczony / The way the transfer should be settled
	System string `json:"system"`

	// Tryb realizacji płatności. Nadrzędna informacja decydująca o tym w jakim trybie zostanie zrealizowana płatność. / Payment execution mode. The superior information deciding which mode is to be used to execute payment.
	ExecutionMode string `json:"executionMode,omitempty"`

	RequestHeader *RequestHeaderCallback `json:"requestHeader"`

	// Tryb pilności / Urgency mode
	DeliveryMode string `json:"deliveryMode"`

	Recipient *RecipientPis `json:"recipient"`

	TransferData *TransferDataCurrencyRequired `json:"transferData"`

	// Czy założyć blokadę (w przypadku np. zlecenia przelewu w dniu wolnym) / Indicates if payment should be holded
	Hold bool `json:"hold,omitempty"`

	// ID transakcji nadany przez TPP / Transaction ID (TPP)
	TppTransactionId string `json:"tppTransactionId"`
}
